ARG TAG
ARG CP_CONNECT_IMAGE
ARG CONNECT_USER
FROM confluentinc/${CP_CONNECT_IMAGE}:${TAG}
ARG TAG
ARG TAG_BASE
ARG CONNECTOR
ARG CONNECT_USER
USER root
RUN  wget http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm && rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm || true && exit 0
RUN yum -y install bind-utils openssl unzip findutils net-tools nc jq which iptables libmnl krb5-workstation krb5-libs && yum clean all && rm -rf /var/cache/yum || true && exit 0
RUN apt-get update; apt-get -y install bind-utils openssl unzip findutils net-tools nc jq which iptables iproute && rm -rf /var/lib/apt/lists/* || true && exit 0
COPY jmx_prometheus_javaagent-0.12.0.jar /usr/share/
RUN mkdir -p /usr/share/confluent-hub-components && chown -R ${CONNECT_USER}:${CONNECT_USER} /usr/share/confluent-hub-components /etc/kafka /etc/schema-registry
USER ${CONNECT_USER}
COPY ${CONNECTOR} /tmp
RUN confluent-hub install --no-prompt /tmp/${CONNECTOR}
