ARG TAG
ARG CP_CONNECT_IMAGE
FROM confluentinc/${CP_CONNECT_IMAGE}:${TAG}
ARG TAG
ARG TAG_BASE
ARG CONNECTOR
USER root
RUN yum -y install bind-utils openssl unzip findutils net-tools nc jq which iptables || true && exit 0
RUN apt-get update; apt-get -y install bind-utils openssl unzip findutils net-tools nc jq which iptables || true && exit 0
COPY jmx_prometheus_javaagent-0.12.0.jar /usr/share/
COPY ${CONNECTOR} /tmp
RUN confluent-hub install --no-prompt /tmp/${CONNECTOR}
