name: CI

on:
  push:
    branches:
      - master

  schedule:
     - cron: '0 17 * * *' # every day at 5pm

  workflow_dispatch:

jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create readme image
        run: bash scripts/create-readme-image.sh "7.3.2"
        
      - name: Update README
        run: |
          COMMIT_MESSAGE=$(./scripts/update-readme.sh "7.3.2")
          echo "commit_msg=$COMMIT_MESSAGE" >> $GITHUB_ENV
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: ${{ env.commit_msg }}
          files: ./README.md
          name: Vincent de Saboulin

